// frontend-ng/src/app/utils/spinner/spinner.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
    selector: 'spinner',
    templateUrl: './spinner.component.html',
    styleUrls: ['./spinner.component.css']
})
export class SpinnerComponent implements OnInit {

    /** Specify text to display below spinner */
    @Input() text: string;

    constructor() {
    }

    ngOnInit() {
    }
}

<div class="columns is-centered">
    <div class="column is-12-mobile is-4-desktop">
        <div class="spinner">
            <div class="double-bounce1"></div>
            <div class="double-bounce2"></div>
        </div>
        <p class="has-text-centered">{{ text }}</p>
    </div>
</div>

// frontend/src/components/utils/spinner.tsx
import * as React from 'react';
import './spinner.css';

interface SpinnerProps {
  text: string | null;
}

/**
 * Spinner created by Tobias Ahlin. Licensed under MIT license.
 *
 * https://github.com/tobiasahlin/SpinKit
 */
export class Spinner extends React.Component<SpinnerProps, {}> {

  constructor(props: SpinnerProps) {
    super(props);
  }

  render() {
    let text = null;
    if (this.props.text !== null) {
      text = (<h6>{this.props.text}</h6>);
    }
    return (
      <div className="columns is-centered">
        <div className="column is-12-mobile is-4-desktop">
          <div className="spinner">
            <div className="double-bounce1"/>
            <div className="double-bounce2"/>
          </div>
          {text}
        </div>
      </div>
    );
  }
}
