// frontend/src/components/containers/entry-editor.tsx
import { EtchedApi } from '../../etched-api';
import { EtchEncrypter } from '../../crypto/crypto';
import * as React from 'react';
import { Entry } from '../../models/entry';
import { Link } from 'react-router-dom';
import { Etch } from '../../models/etch';

interface EntryEditorProps {
  etchedApi: EtchedApi;
  encrypter: EtchEncrypter;
  entry?: Entry;
}

interface EntryEditorState {
  /** indicates whether a request is in flight */
  title: string;
  /** current etch contents */
  currentText: string;
  /** list of etches */
  etches: string[];
}

/** Amount of elapsed inactivity before etch is saved */
const ETCH_TIMEOUT = 5 * 1000;

const ESC_KEY_CODE = 27;
const ENTER_KEY_CODE = 13;

const ENTRY_NOT_CREATED = 'NOT_CREATED';
const ENTRY_CREATING = 'ENTRY_CREATING';
const ENTRY_CREATED = 'ENTRY_CREATED';

const ENTRY_EDITOR_ID = 'entry-editor';

export class EntryEditor extends React.Component<EntryEditorProps, EntryEditorState> {

  /** indicates that the user pressed escape when editing the title */
  escapedEditingTitle: boolean;

  /** title that is currently being edited (but yet saved) */
  editingTitle: string;

  /** timestamp of last edit (millis since epoch) */
  recentEdit: number;

  /** entry created */
  entryCreated: boolean;

  /** etches not yet posted */
  queuedEtches: string[];

  /** the timer/interval used to post queued etches */
  queuedEtchInterval: number;

  /** the timer/interval used to etch entries due to inactivity */
  etchingInterval: number;

  /** the current state of the entry */
  entryCreationState: string;

  /** the current entry */
  entry?: Entry;

  constructor(props: EntryEditorProps) {
    super(props);

    this.state = {
      title: new Date().toString(),
      currentText: '',
      etches: [],
    };

    this.entry = this.props.entry;
    this.editingTitle = '';
    this.escapedEditingTitle = false;
    this.recentEdit = Date.now();
    this.entryCreated = false;
    this.queuedEtches = [];
    this.entryCreationState = ENTRY_NOT_CREATED;
  }

  componentDidMount() {
    this.etchingInterval = window.setInterval(() => {
      // If user hasn't made any changes in `ETCH_TIMEOUT` seconds, we update
      if (Date.now() - this.recentEdit >= ETCH_TIMEOUT && this.state.currentText !== '') {
        this.updateContent();
      }
    },                                        500);

    this.queuedEtchInterval = window.setInterval(() => {
      if (this.entryCreationState === ENTRY_CREATED) {
        this.postEtches();
      }
    },                                           10000);
  }

  componentWillUnmount() {
    console.log('Unmounting. Posting all queued etches');
    if (this.entry !== undefined) {
      // Can't be queued etches if the entry hasn't yet been created
      this.postEtches();
    }

    // clear intervals
    window.clearInterval(this.etchingInterval);
    window.clearInterval(this.queuedEtchInterval);
  }

  onEtchChange = (event: React.ChangeEvent<HTMLDivElement>) => {
    this.recentEdit = Date.now();
    this.setState({currentText: event.target.innerText});
  }

  updateContent = () => {
    console.log('Etching');
    const items = this.state.etches;
    const text = this.state.currentText;
    items.push(text);

    if (items.length > 0 && this.entryCreationState === ENTRY_NOT_CREATED) {
      this.createEntry();
    }

    this.setState({currentText: ''});
    this.queuedEtches.push(text);
    console.log(this.state);

    // This element may not exist in the case when a user navigates away from a page and the
    // component posts all queued etches during componentWillUnmount
    let contentEditorElement = document.getElementById(ENTRY_EDITOR_ID);
    if (contentEditorElement !== null) {
      contentEditorElement.textContent = '';
    }
  }

  onKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    // On enter update content
    if (e.keyCode === ENTER_KEY_CODE && !e.shiftKey) {
      e.preventDefault();
      this.updateContent();
    }
  }

  saveTitle = (title: string) => {
    console.log(`Saving new title '${title}'`);
    this.setState({title: title});
    let titleElement = document.getElementById('etch-title-heading')!!;
    titleElement.setAttribute('contenteditable', 'false');
    this.createEntry();
  }

  resetTitle = () => {
    let titleElement = document.getElementById('etch-title-heading')!!;
    // Reset title to saved title
    // We have to manually edit this...
    titleElement.textContent = this.state.title;
    this.escapedEditingTitle = false;
  }

  renderTitle() {

    return (
      <h4
        className="etched-editable"
        id="etch-title-heading"
        data-placeholder="Title"
        onKeyDown={(e: React.KeyboardEvent<HTMLInputElement>) => {
          let titleElement = document.getElementById('etch-title-heading')!!;

          // If escape is pressed, cancel title editing and revert to old title
          if (e.keyCode === ESC_KEY_CODE) {
            this.escapedEditingTitle = true;
            // Set contentenabled=false, so that we exit the edit mode
            titleElement.setAttribute('contenteditable', 'false');
          } else if (e.keyCode === ENTER_KEY_CODE) {
            titleElement.blur();
          }
        }}
        onClick={() => {
          // Enable content editable on click
          let titleElement = document.getElementById('etch-title-heading')!!;
          titleElement.setAttribute('contenteditable', 'true');
          // Need to set focus, otherwise another click is required to enter edit mode
          titleElement.focus();
        }}

        onBlur={(e) => {
          let title = e.currentTarget.textContent!!;
          // If we pressed escape or title is empty, don't save
          if (this.escapedEditingTitle || title === null || title.trim() === '') {
            this.resetTitle();
          } else {
            this.saveTitle(e.currentTarget.innerText);
          }
        }}
      >
        {this.state.title}
      </h4>
    );
  }

  createEntry() {
    if (this.entryCreationState !== ENTRY_NOT_CREATED) {
      return;
    }

    const title = this.state.title;
    console.log(`Creating entry '${title}'`);

    this.entryCreationState = ENTRY_CREATING;
    this.props.etchedApi.postEntry(title)
      .then(entry => {
        console.log(`Posted entry with id ${entry.id}`);
        this.entry = entry;
        this.entryCreationState = ENTRY_CREATED;
      });
  }

  postEtches() {
    let {etchedApi, encrypter} = this.props;

    let entry = this.entry;
    if (entry === undefined || entry === null) {
      throw new Error(`Attempted to post an etch to a non existent entry`);
    }

    let etches = this.queuedEtches.slice(0);

    if (etches.length === 0) {
      return;
    }

    let encrypting = etches.map((etch: string) => encrypter.encrypt(etch));
    Promise.all(encrypting)
      .then((encryptedEtches: Etch[]) => {
        // TODO: Handle queue getting really large e.g. 100 elements
        // Break it up against multiple requests???
        // TODO: Why do we need the !!? We've checked that it's not null or undefined earlier...
        console.log(`Posting ${encryptedEtches.length} etches`);
        return etchedApi.postEtches(entry!!.id, encryptedEtches);
      })
      .then((savedEtches: Etch[]) => {
        // Remove the posted etches from the queue
        this.queuedEtches = this.queuedEtches.slice(savedEtches.length);
        console.log(`Successfully posted ${savedEtches.length} etches`);
      });
  }

  render() {
    const title = this.renderTitle();

    let renderedEtches = null;
    if (this.state.etches.length > 0) {
      let listItems: JSX.Element[] = [];
      this.state.etches.forEach((etch: string, index: number) => {
        listItems.push(<li key={index}>{etch}</li>);
      });
      renderedEtches = <ul>{listItems}</ul>;
    }

    return (
      <div className="columns is-centered">
        <div className="column is-12-mobile is-8-tablet is-8-desktop">
          <div className="columns has-text-left">
            {title}
          </div>
          <div className="columns has-text-left">
            {renderedEtches}
          </div>
          <div className="columns has-text-left">
            <form className="full-width" onSubmit={this.updateContent}>
              <div
                id={ENTRY_EDITOR_ID}
                className="etched-editable"
                contentEditable={true}
                data-placeholder="What's on your mind?"
                // TODO: Is it okay to use onInput?
                onInput={this.onEtchChange}
                onKeyDown={this.onKeyDown}
              />
            </form>
          </div>
          <Link to="/">
            <button className="button is-primary">
              Home
            </button>
          </Link>
        </div>
      </div>
    );
  }
}

// frontend-ng/src/app/etches/entry-editor/entry-editor.component.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { EntryEntity } from '../../models/entry-entity';
import { EtchedApiService } from '../../services/etched-api.service';
import { Encrypter, TEST_KEY_PAIR } from '../../services/encrypter';
import { Base64Str, EncryptedEntity } from '../../models/encrypted-entity';
import { Observable } from 'rxjs';

const ETCH_TIMEOUT = 5 * 1000;

const ENTER_KEY = 'Enter';
const ESC_KEY = 'Escape';

const ENTRY_NOT_CREATED = 'NOT_CREATED';
const ENTRY_CREATING = 'ENTRY_CREATING';
const ENTRY_CREATED = 'ENTRY_CREATED';

// TODO: This feels like it's doing way too much and can be broken down some more

@Component({
    selector: 'app-entry-editor',
    templateUrl: './entry-editor.component.html',
    styleUrls: ['./entry-editor.component.css'],
})
export class EntryEditorComponent implements OnInit, OnDestroy {

    // <TITLE STUFF>
    /** title of entry */
    title: string;

    /** the previous title before the user began editing the title, used to allow users to
     * cancel editing the title and revert back to the previous title
     */
    private prevTitle: string;

    /** specifies whether the title is currently editable */
    titleIsEditable: boolean;

    /** the title html element */
    @ViewChild('titleBox')
    titleElement: ElementRef;

    /** indicates that the user pressed escape when editing the title */
    escapedEditingTitle: boolean;
    // </TITLE STUFF>

    /** list of etches */
    etches: string[];

    /** timestamp of last edit (millis since epoch) */
    recentEdit: number;

    /** etches not yet posted */
    queuedEtches: string[];

    /** the timer/interval used to post queued etches */
    queuedEtchInterval: number;

    /** the timer/interval used to etch entries due to inactivity */
    etchingInterval: number;

    /** the current state of the entry */
    entryCreationState: string;

    /** the current entry */
    entry?: EntryEntity;

    encrypter: Encrypter;

    /** The content of the etch that is currently being edited */
    currentEtchContent: string;

    constructor(protected etchedApi: EtchedApiService) {
    }

    ngOnInit() {
        // title stuff
        this.title = new Date().toString();
        this.prevTitle = this.title;
        this.titleIsEditable = false;
        this.escapedEditingTitle = false;

        this.etches = [];
        this.entry = undefined;
        this.queuedEtches = [];

        this.recentEdit = Date.now();
        this.entryCreationState = ENTRY_NOT_CREATED;
        this.currentEtchContent = '';

        // TODO: Provide the encrypter via injection
        Encrypter.from(TEST_KEY_PAIR, 'passphrase')
            .then(encrypter => this.encrypter = encrypter);

        this.etchingInterval = window.setInterval(() => {
            // If user hasn't made any changes in `ETCH_TIMEOUT` seconds, we update
            if (this.entryCreationState == ENTRY_CREATED &&
                (Date.now() - this.recentEdit) >= ETCH_TIMEOUT) {
                this.etch();
            }
        }, 1000);

        this.queuedEtchInterval = window.setInterval(() => {
            this.postEtches();
        }, 5000);
    }

    ngOnDestroy(): void {
        console.log('Unmounting. Posting all queued etches');
        if (this.entry !== undefined) {
            // Can't be queued etches if the entry hasn't yet been created
            this.postEtches();
        }

        // clear intervals
        window.clearInterval(this.etchingInterval);
        window.clearInterval(this.queuedEtchInterval);
    }

    onTitleClick() {
        this.prevTitle = this.titleElement.nativeElement.textContent;
        this.titleIsEditable = true;
    }

    onTitleChange(key: string) {
        if (key === ENTER_KEY) {
            console.info('finished editing title');
            this.titleElement.nativeElement.blur();
        } else if (key === ESC_KEY) {
            console.info('escaping title edit');
            this.escapedEditingTitle = true;
            this.titleIsEditable = false;
        }
    }

    onTitleBlur(event: FocusEvent) {
        let newTitle = (event.currentTarget as any).textContent!!.trim();

        // If we pressed escape or title is empty, don't save
        if (this.escapedEditingTitle || newTitle === null || newTitle.trim() === '') {
            console.info('resetting title');

            this.title = this.prevTitle;
            this.titleElement.nativeElement.textContent = this.prevTitle;
            this.escapedEditingTitle = false;
        } else {
            console.info(`Setting title: ${newTitle}`);
            this.title = newTitle;
            this.prevTitle = newTitle;
            this.titleElement.nativeElement.textContent = newTitle;
            this.titleIsEditable = false;
        }
    }

    /**
     * Responds to key events
     *
     * This checks if "enter" was pressed and will finalize the etch if it was.
     *
     * This is called before the input event handler `onEtchInput`. This allows us to finalize the
     * etch when enter is pressed.
     *
     * @param event
     */
    onEtchKeydown(event: KeyboardEvent) {
        // Update the recent edit date of the etch
        this.recentEdit = Date.now();

        // We don't want to update the etch if the user pressed "shift + enter"
        if (event.key === ENTER_KEY && !event.shiftKey) {
            // Finalize the etch
            // preventing default event to prevent a new line
            // preventing the default event will also stop the event from propagating to onEtchInput
            event.preventDefault();
            this.etch();
        }
    }

    /**
     * Responds to input changes on the etch
     *
     * This is invoked after `onEtchKeydown` and simply updates the current value with the new
     * value
     *
     * @param event
     */
    onEtchInput(event) {
        // Keydown is called first
        this.currentEtchContent = event.target.innerText;
    }

    /**
     * Etch the current etch
     *
     * This actually finalizes the current etch and it can't be edited beyond this point
     */
    etch() {
        // Create an entry only when the user has writes their first etch
        // TODO: Allow users to edit entry titles
        if (this.etches.length > 0 && this.entryCreationState === ENTRY_NOT_CREATED) {
            this.createEntry();
        }

        const text = this.currentEtchContent.trim();
        if (text === '') {
            return;
        }

        // TODO: Add metadata representation of etch
        console.info(`Etching ${text}`);
        // Push the current etch to the list of etches being displayed
        this.etches.push(text);

        // TODO: Can we bind a variable to the text content of this element?
        // Reset the etch
        this.currentEtchContent = '';

        // this.etchEditorElement.nativeElement.textContent = '';
        // Add the etch to the queue so it can be encrypted and posted to the server
        this.queuedEtches.push(text);
    }

    /**
     * Creates an entry
     */
    createEntry() {
        if (this.entryCreationState !== ENTRY_NOT_CREATED) {
            // The entry has already been created, don't need to do anything here
            return;
        }

        console.log(`Creating entry`);
        this.entryCreationState = ENTRY_CREATING;

        this.encrypter.encrypt(this.title)
            .then(ciphertext => {
                this.etchedApi.createEntry(ciphertext)
                    .subscribe(entry => {
                        console.log(`Created entry with id ${entry.id}`);
                        this.entryCreationState = ENTRY_CREATED;
                        this.entry = entry;
                    });
            })
    }

    /**
     * Post the queued etches to the backend
     */
    postEtches() {
        // slice(0) creates a copy of the array
        let etches = this.queuedEtches.slice(0);

        if (etches.length === 0) {
            console.info('No queued etches');
            return;
        }

        if (this.entry === undefined || this.entry === null) {
            console.info('Entry is not yet created, waiting til it is created');
            return;
        }

        // TODO: Improve performance
        // It's blocking the main thread on my 2017 Macbook Pro. That's way too slow!

        // Encrypt all the etches
        console.info('Starting encryption of etches');
        let encrypting = etches.map((etch: string) => this.encrypter.encrypt(etch));

        // Wait for all them to encrypt and then post them in a single request
        Promise.all(encrypting)
            .then((encryptedEtches: Base64Str[]) => {
                // TODO: Handle queue getting really large e.g. 100 elements
                // Break it up against multiple requests???
                console.info('Encryption finished');
                console.info(`Posting ${encryptedEtches.length} etches`);
                return this.etchedApi.postEtches(this.entry.id, encryptedEtches);
            })
            .then((savedEtchesObs: Observable<EncryptedEntity[]>) => {
                savedEtchesObs.subscribe(savedEtches => {
                    // Remove the posted etches from the queue
                    this.queuedEtches = this.queuedEtches.slice(savedEtches.length);
                    console.info(`Successfully posted ${savedEtches.length} etches`);
                });
            });
    }
}

<div *ngIf="etchedApi.getUser()" class="columns is-centered">
    <div class="column is-12-mobile is-8-tablet is-8-desktop">
        <div class="columns has-text-left">
            <h4 class="etched-editable"
                #titleBox
                id="entry-title-heading"
                data-placeholder="Title"
                (keydown)="onTitleChange($event.key)"
                (click)="onTitleClick()"
                (blur)="onTitleBlur($event)"
                [attr.contenteditable]="titleIsEditable"
            >
                {{ title }}
            </h4>
        </div>
        <div class="columns has-text-left">
            <ul>
                <li *ngFor="let e of etches">{{ e }}</li>
            </ul>
        </div>
        <div class="columns has-text-left">
            <div
                #entryEditor
                id="entry-editor"
                class="etched-editable"
                contentEditable="true"
                data-placeholder="What's on your mind?"
                [textContent]="currentEtchContent"
                (input)="onEtchInput($event)"
                (keydown)="onEtchKeydown($event)"
            ></div>
            <!--<div-->
            <!--#etchEditor-->
            <!--id="entry-editor"-->
            <!--class="etched-editable"-->
            <!--contentEditable="true"-->
            <!--data-placeholder="What's on your mind?"-->
            <!--(keydown)="onEtchKeydown($event)"-->
            <!--&gt;</div>-->
        </div>
    </div>
</div>
