// frontend/src/components/login/login.tsx
import * as React from 'react';
import { ChangeEvent } from 'react';
import { EtchedApi } from '../../etched-api';
import { EtchedUser } from '../../models/etched-user';
import { FormField } from '../utils/form-field';
import { Spinner } from '../utils/spinner';

interface LoginProps {
  etchedApi: EtchedApi;

  setUser(user: EtchedUser): void;
}

interface LoginState {
  username: string;
  password: string;
  loggingIn: boolean;
}

export class Login extends React.Component<LoginProps, LoginState> {

  handleSubmit = (event: React.SyntheticEvent<EventTarget>) => {
    event.preventDefault();
    this.setState({loggingIn: true});
    console.log(`Logging in User[username='${this.state.username}']`);

    this.props.etchedApi.login(this.state.username, this.state.password)
      .then(() => {
        // After login, get the user details
        return this.props.etchedApi.self();
      })
      .then(user => {
        // TODO: reevaluate auth API
        // We have to send another request. Is this a problem with our API?
        this.setState({loggingIn: false});
        this.props.setUser(user);
      })
      .catch(e => console.error(e));
  }

  onUsernameChanged = (event: ChangeEvent<HTMLInputElement>) => {
    this.setState({username: event.target.value});
  }

  onPasswordChanged = (event: ChangeEvent<HTMLInputElement>) => {
    this.setState({password: event.target.value});
  }

  constructor(props: LoginProps) {
    super(props);
    this.state = {
      username: '',
      password: '',
      loggingIn: false,
    };
  }

  render() {
    if (this.state.loggingIn) {
      return <Spinner text="Logging in"/>;
    }

    return (
      <div className="columns is-centered">
        <div className="column is-12-mobile is-4-desktop">
          <h3>Login</h3>
          <form className="control" onSubmit={this.handleSubmit}>
            <FormField>
              <label className="label">Username</label>
              <input
                className="input"
                type="text"
                placeholder="Username"
                name="username"
                value={this.state.username}
                onChange={this.onUsernameChanged}
              />
            </FormField>
            <FormField>
              <label className="label">Password</label>
              <input
                className="input"
                type="password"
                placeholder="Password"
                name="password"
                value={this.state.password}
                onChange={this.onPasswordChanged}
              />
            </FormField>
            <FormField>
              <button className="button is-primary">Login</button>
            </FormField>
          </form>
        </div>
      </div>
    );
  }
}

// frontend-ng/src/app/user/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { EtchedApiService } from '../../services/etched-api.service';
import { FormBuilder } from '@angular/forms';
import { EtchedUser } from '../../models/etched-user';
import { PASSWORD_VALIDATORS, USERNAME_VALIDATORS } from '../form-utils';
import { EncrypterService } from '../../services/encrypter.service';
import { Encrypter, TEST_KEY_PAIR } from '../../services/encrypter';

@Component({
    selector: 'login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

    loginForm = this.fb.group({
        username: ['', USERNAME_VALIDATORS],
        password: ['', PASSWORD_VALIDATORS],
    });

    /** login request is in flight */
    inFlight: boolean;

    constructor(private fb: FormBuilder,
                private etchedApi: EtchedApiService,
                private encrypterService: EncrypterService) {
        this.inFlight = false;
    }

    ngOnInit() {
        // TODO: Create a separate component for downloading the key and entering the passphrase
        Encrypter.from(TEST_KEY_PAIR, 'passphrase')
            .then(encrypter => this.encrypterService.encrypter = encrypter);
    }

    onSubmit() {
        const {username, password} = this.loginForm.value;
        console.info(`logging in ${username}`);
        this.inFlight = true;
        this.etchedApi.login(username, password)
            // Do nothing with this subscription
            .subscribe(() => this.inFlight = false);
    }

    get user(): EtchedUser | null {
        return this.etchedApi.getUser();
    }

    showSpinner(): boolean {
        return this.inFlight || this.encrypterService.encrypter === null;
    }
}

<div class="columns is-centered">
    <div *ngIf="!showSpinner()" class="column is-12-mobile is-4-desktop">
        <div *ngIf="user === null">
            <h3 class="title">Login</h3>
            <form [formGroup]="loginForm"
                  class="control"
                  (ngSubmit)="onSubmit()">
                <div class="field">
                    <div class="control">
                        <label class="label">Username</label>
                        <input
                            class="input"
                            type="text"
                            placeholder="Username"
                            name="username"
                            formControlName="username"
                        />
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label">Password</label>
                        <input
                            class="input"
                            type="password"
                            placeholder="Password"
                            name="password"
                            formControlName="password"
                        />
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button
                            class="button is-primary"
                            type="submit"
                            [disabled]="!loginForm.valid">
                            Login
                        </button>
                    </div>
                </div>
                <p>
                    Form Status: {{ loginForm.status }}
                </p>
            </form>
        </div>
        <div *ngIf="user !== null">
            <p>Logged in as user {{ user.username }}</p>
        </div>
    </div>
    <div *ngIf="showSpinner()" class="column is-12-mobile is-4-desktop">
        <spinner [text]="'Logging in'"></spinner>
    </div>
</div>
