// frontend-ng/src/app/user/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { EMAIL_VALIDATORS, PASSWORD_VALIDATORS, USERNAME_VALIDATORS } from '../form-utils';
import { EtchedApiService } from '../../services/etched-api.service';

@Component({
    selector: 'register',
    templateUrl: './register.component.html',
    styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

    registerForm = this.fb.group({
        username: ['', USERNAME_VALIDATORS],
        password: ['', PASSWORD_VALIDATORS],
        email: ['', EMAIL_VALIDATORS],
    });

    constructor(private fb: FormBuilder,
                private etchedApi: EtchedApiService) {
    }

    ngOnInit() {
    }

    onSubmit() {
        console.info(this.registerForm.value);
        let {username, password, email} = this.registerForm.value;
        if (email === undefined || email.trim() === '') {
            console.info('Registering without an email');
            email = null;
        }
        this.etchedApi.register(
            username,
            password,
            email
        )
            .subscribe(u => {
                console.info(`Registered ${JSON.stringify(u)}`);
            });
    }
}

<div class="columns is-centered">
    <div *ngIf="inFlight === false" class="column is-12-mobile is-4-desktop">
        <h3 class="title">Register</h3>
        <form
            [formGroup]="registerForm"
            class="control"
            (submit)="onSubmit()"
        >
            <div class="field">
                <div class="control">
                    <label class="label">Username</label>
                    <input
                        class="input"
                        type="text"
                        placeholder="Username"
                        name="username"
                        formControlName="username"
                    />
                </div>
            </div>
            <!--<div class="field">-->
                <!--<div class="control">-->
                    <!--<label class="label">Email</label>-->
                    <!--<input-->
                        <!--class="input"-->
                        <!--type="text"-->
                        <!--placeholder="Email"-->
                        <!--formControlName="email"-->
                    <!--/>-->
                <!--</div>-->
            <!--</div>-->
            <div class="field">
                <div class="control">
                    <label class="label">Password</label>
                    <input
                        class="input"
                        type="password"
                        placeholder="Password"
                        name="password"
                        formControlName="password"
                    />
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <button
                        type="submit"
                        class="button is-primary"
                        [disabled]="!registerForm.valid">
                        Submit
                    </button>
                </div>
            </div>
            <p>
                Form Status: {{ registerForm.status }}
            </p>
            <div style="padding-top: 10px">
                <!--TODO: Add router link to login page-->
                Already have an account? <a routerLink="/login">Login here</a>
            </div>
        </form>
    </div>
    <div *ngIf="inFlight" class="column is-12-mobile is-4-desktop">
        <spinner [text]="'Registering'"></spinner>
    </div>
</div>

// frontend/src/components/register/register.tsx
import * as React from 'react';
import { ChangeEvent } from 'react';
import { EtchedApi } from '../../etched-api';
import { EtchedUser } from '../../models/etched-user';
import { FormField } from '../utils/form-field';
import { Link } from 'react-router-dom';
import { Spinner } from '../utils/spinner';
import { Redirect } from 'react-router';

interface RegisterState {
  username: string;
  email: string;
  password: string;
  registering: boolean;
  registered: boolean;
}

interface RegisterProps {
  etchedApi: EtchedApi;

  setUser(user: EtchedUser): void;
}

export class Register extends React.Component<RegisterProps, RegisterState> {

  constructor(props: RegisterProps) {
    super(props);
    this.state = {
      username: '',
      email: '',
      password: '',
      registered: false,
      registering: false,
    };
  }

  handleSubmit = (event: React.SyntheticEvent<EventTarget>) => {
    event.preventDefault();
    this.setState({registering: true});

    const {username, password, email} = this.state;
    console.log(`Registering User[username='${username}']`);

    this.props.etchedApi.register(username, email, password)
      .then((user: EtchedUser) => {
        // TODO: Should user perform login or should we just handle it in code?
        // Have to perform a login after registering
        console.log(`Getting auth tokens for ${user.username}`);
        this.props.etchedApi.login(username, password)
          .then(() => {
            this.setState({registering: false, registered: true});
            this.props.setUser(user);
          });
      });
  }

  onUsernameChanged = (event: ChangeEvent<HTMLInputElement>) => {
    this.setState({username: event.target.value});
  }

  onPasswordChanged = (event: ChangeEvent<HTMLInputElement>) => {
    this.setState({password: event.target.value});
  }

  onEmailChanged = (event: ChangeEvent<HTMLInputElement>) => {
    this.setState({email: event.target.value});
  }

  render() {

    if (this.state.registering) {
      return <Spinner text="Creating account"/>;
    } else if (this.state.registered) {
      return <Redirect to="/configure-passphrase"/>;
    }
    return (
      <div className="columns is-centered">
        <div className="column is-12-mobile is-4-desktop">
          <h3>Register</h3>
          <form className="control" onSubmit={this.handleSubmit}>
            <FormField>
              <label className="label">Username</label>
              <input
                className="input"
                type="text"
                placeholder="Username"
                name="username"
                value={this.state.username}
                onChange={this.onUsernameChanged}
              />
            </FormField>
            <FormField>
              <label className="label">Email</label>
              <input
                className="input"
                type="text"
                placeholder="Email"
                value={this.state.email}
                onChange={this.onEmailChanged}
              />
            </FormField>
            <FormField>
              <label className="label">Password</label>
              <input
                className="input"
                type="password"
                placeholder="Password"
                name="password"
                value={this.state.password}
                onChange={this.onPasswordChanged}
              />
            </FormField>
            <FormField>
                <button className="button is-primary">Submit</button>
            </FormField>
            <div style={{'paddingTop': '10px'}}>
              Already have an account? <Link to="/login">Log in here</Link>
            </div>
          </form>
        </div>
      </div>
    );
  }
}
